# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f00d4a646b980400d4b61122dc028f711c7fade10427a42ca3823011cdba0d28850bea067df63a325ec1e477d53948f677717a67fd1b0b12183964d5bfddd06

test:
  secret_key_base: a0125533a0a9ccbc82e3a12adc232db0e6422fa6305f15b6bc8e3efa2296f115e4c6b70f65c6799d3e5ac1df220a58d11397ed2def91de2391fe221fe8abc189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
